### ISSUE TITLE
Problem when using pioarduino with ESP32C6 and ESPHome

### ISSUE THREAD

**Issue by majuss** [pioarduino/platform-espressif32#171]
### PROBLEM DESCRIPTION
I'am using the ESPHome 2025.4.1 to compile a ESP32C6 firmware. ESPHome was installed with uv on macOS 154.1 with python3.13.3 Here is the YAML:

```yaml
esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: arduino
    platform_version: 55.03.30-alpha1
```

When I do `esphome compile esp.yaml`
I get:

```
*** missing SConscript file '/Users/A79006593/.platformio/packages/framework-arduinoespressif32/tools/platformio-build-esp32c6.py'
File "/Users/A79006593/.platformio/packages/framework-arduinoespressif32/tools/platformio-build.py", line 161, in <module>
```
And it's aborting the build

### TO REPRODUCE
See description

### EXPECTED BEHAVIOUR
Build passes
